spring.application.name=ApiGateway
server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://USERSERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/user/**

spring.cloud.gateway.routes[1].id=hotel-service
spring.cloud.gateway.routes[1].uri=lb://HOTELSERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/hotel/**

spring.cloud.gateway.routes[2].id=rating-service
spring.cloud.gateway.routes[2].uri=lb://RATINGSERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/rating/**